title: Carlos Nosa
profession: Matem치tico
location: Bogot치, Colombia
age: 21 a침os
email: cnosa@unal.edu.co
tab_title: Carlos Nosa | Matem치tico


description: Portafolio profesional
theme: jekyll-theme-minimal
linkedin_url: https://www.linkedin.com/in/carlos-enrique-nosa-guzman-069258300/
github_url: https://github.com/cnosa
instagram_url: https://www.instagram.com/nosanonimo/
plugins:
  - jekyll-polyglot
  - jekyll-paginate
defaults:
  - scope:
      path: ""
    values:
      layout: default
      lang: es
languages: ["es", "en"]
exclude_from_localizations: ["assets", "images"]
