title: Carlos Nosa
description: Portafolio profesional
theme: jekyll-theme-minimal
linkedin_url: https://www.linkedin.com/in/carlos-enrique-nosa-guzman-069258300/
github_url: https://github.com/cnosa
instagram_url: https://www.instagram.com/nosanonimo/
plugins:
  - jekyll-polyglot
defaults:
  - scope:
      path: ""
    values:
      layout: default

plugins:
  - jekyll-polyglot