title: Carlos Nosa
email: cnosa@unal.edu.co
tab_title: Carlos Nosa | Web
url: https://cnosa.github.io/CNosaWebsite/
# Español
es:
  name: Carlos Nosa
  profession: Matemático
  status: En proceso de formación
  location: Bogotá, Colombia
  age: 21 años
  meta_description: "Portafolio profesional de Carlos Nosa, Matemático en formación"
  nav_links:
    home: "Inicio"
    blog: "Blog"
en:
  name: Carlos Nosa
  profession: Mathematician
  status: In formation process
  location: Bogotá, Colombia
  age: 21 years
  meta_description: "Professional portfolio of Carlos Nosa, Mathematician in training"
  nav_links:
    home: "Home"
    blog: "Blog"





description: Proffesional portfolio
theme: jekyll-theme-minimal
linkedin_url: https://www.linkedin.com/in/carlos-enrique-nosa-guzman-069258300/
github_url: https://github.com/cnosa
instagram_url: https://www.instagram.com/nosanonimo/
plugins:
  - jekyll-polyglot
  - jekyll-paginate
defaults:
  - scope:
      path: ""
    values:
      layout: default
      lang: es
languages: ["es", "en"]
exclude_from_localizations: ["assets", "images"]

