# ======================
# Configuración Básica
# ======================
title: Carlos Nosa
description: "Portafolio profesional de Carlos Nosa - Matemático en formación"
baseurl: ""
url: "https://cnosa.github.io/CNosaWebsite/"
theme: jekyll-theme-minimal
plugins:
  - jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0

# ======================
# Metadatos Globales
# ======================
tab_title: "Carlos Nosa | Web"
email: cnosa@unal.edu.co

# ======================
# Enlaces de Contacto
# ======================
linkedin_url: "https://www.linkedin.com/in/carlos-enrique-nosa-guzman-069258300/"
github_url: "https://github.com/cnosa"
instagram_url: "https://www.instagram.com/nosanonimo/"

# ======================
# Configuración Multidioma
# ======================
languages: ["es", "en"]
exclude_from_localizations: ["assets", "images"]
defaults:
  - scope:
      path: ""
    values:
      layout: default
      lang: es

# ======================
# Contenido en Español
# ======================
es:
  name: "Carlos Nosa"
  profession: "Matemático"
  status: "En proceso de formación"
  location: "Bogotá, Colombia"
  age: "21 años"
  nav:
    home: "Inicio"
    blog: "Blog"
  cv: "/assets/cv_es.pdf"
  cv_text: "Hoja de Vida"

# ======================
# English Content
# ======================
en:
  name: "Carlos Nosa"
  profession: "Mathematician"
  status: "In formation process"
  location: "Bogotá, Colombia"
  age: "21 years"
  nav:
    home: "Home"
    blog: "Blog"
  cv: "/assets/cv_en.pdf"
  cv_text: "Resume"

# ======================
# Plugins
# ======================
plugins:
  - jekyll-polyglot
  - jekyll-paginate

# ======================
# Opciones de Build
# ======================
markdown: kramdown
highlighter: rouge
sass:
  style: compressed