title: Carlos Nosa
email: cnosa@unal.edu.co
tab_title: Carlos Nosa | Web

# Español
es:
  name: Carlos Nosa
  profession: Matemático
  status: En proceso de formación
  location: Bogotá, Colombia
  age: 21 años

en:
  name: Carlos Nosa
  profession: Mathematician
  status: In formation process
  location: Bogotá, Colombia
  age: 21 years




description: Proffesional portfolio
theme: jekyll-theme-minimal
linkedin_url: https://www.linkedin.com/in/carlos-enrique-nosa-guzman-069258300/
github_url: https://github.com/cnosa
instagram_url: https://www.instagram.com/nosanonimo/
plugins:
  - jekyll-polyglot
  - jekyll-paginate
defaults:
  - scope:
      path: ""
    values:
      layout: default
      lang: es
languages: ["es", "en"]
exclude_from_localizations: ["assets", "images"]


nav_links_es:
  home: "Inicio"
  blog: "Blog"

nav_links_en:
  home: "Home"
  blog: "Blog"