title: Carlos Nosa
email: cnosa@unal.edu.co
tab_title: Carlos Nosa | Web

# Español
name_es: Carlos Nosa
profession_es: Matemático
status_es: En proceso de formación
location_es: Bogotá, Colombia
age_es: 21 años

# Inglés
name_en: Carlos Nosa
profession_en: Mathematician
status_en: In formation process
location_en: Bogotá, Colombia
age_en: 21 years



description: Proffesional portfolio
theme: jekyll-theme-minimal
linkedin_url: https://www.linkedin.com/in/carlos-enrique-nosa-guzman-069258300/
github_url: https://github.com/cnosa
instagram_url: https://www.instagram.com/nosanonimo/
plugins:
  - jekyll-polyglot
  - jekyll-paginate
defaults:
  - scope:
      path: ""
    values:
      layout: default
      lang: es
languages: ["es", "en"]
exclude_from_localizations: ["assets", "images"]


nav_links_es:
  home: "Inicio"
  blog: "Blog"

nav_links_en:
  home: "Home"
  blog: "Blog"